### ISSUE TITLE
local development server

### ISSUE THREAD

**Issue by mehimself** [coderefinery/sphinx-lesson#32]
Do we have a convenient solution to preview/test our development locally? 
I consider adding a development server wrapper in python. But I rarely develop in python so I might miss something obvious. What is the most practicable setup for you?

**Comment by mehimself** [comment]
I added a make file which hosts the site at localhost:8000 and auto-compiles/live-reloads

**Comment by rkdarst** [comment]
Great, thanks!  I'll be interested to try this out.

Some things I'd recommend:

pull requests always better, especially once we start having
multiple people working on this.  I usually try to do that, too.

Adding sphinx-autobuild to requirements.txt makes it a dependency of
all installations.  I've usually thought that things for local
building shouldn't be in requirements files, since it's the user's
choice how to make and build it.  But, this is a very small
dependency, and the benefits for usability are probably high.  What do
you think?

For the coderefinery branding, I was going to make a Sphinx extension
for coderefinery, that adds in the favicon.  I will follow up on this
once I can.
