### ISSUE TITLE
Should this repo be a template repo?

### ISSUE THREAD

**Issue by robertodr** [coderefinery/sphinx-lesson#41]
Hello and thanks for sharing this repo! I am wondering what is the best way of using it for developing new lessons. I can fork it and rename it, but the forking relationship is not exactly "correct": most of the contents will be removed or reworked in an incompatible manner. Importing it is also an option, I guess, but it seems [templates](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/) automatize this process somewhat. What are your suggestions?

**Comment by rkdarst** [comment]
We have a separate template repository here:
  https://github.com/coderefinery/sphinx-lesson-template/
This has the minimum amount of stuff to start a new project (though you probably need to copy certain examples from sphinx-lesson itself, since the template is very empty - but has all the framework).

I think you might be the first user from outside the developer circle - if you find things that need improving, we are very eager to hear right now.

**Comment by robertodr** [comment]
A-ha! I should have googled better :) I will for sure report any problems or thoughts for improvement. Thanks for putting this out here!

**Comment by bast** [comment]
Roberto is still part of the family though :-) (now working with Thor)
