### ISSUE TITLE
How to make the side menu collapsible?

### ISSUE THREAD

**Issue by robertodr** [coderefinery/sphinx-lesson#53]

**Comment by rkdarst** [comment]
I think we'd need someone who knows some javascript to do that, or upstream support in sphinx_rtd_theme (https://github.com/readthedocs/sphinx_rtd_theme/pull/698), or to use a different theme.

But there are several other things I do instead, instead of explicit collapse toggle:
- I make the window the width I want, and then increase the font size.  After font size increases enough, the sidebar collapses itself (when it switches to the mobile layout).  This is basically what I always do in presentations and actual lessons.  It's possible it might not work with some particular presentation modes + font sizes, but... it's always been surprisingly practical to me.
- [sphinx_minipres](https://github.com/coderefinery/sphinx-minipres) can help you go to presentation mode.  Add `?plain=1` to the URL and sidebar goes away.  Add `?minipres=1` to the URL and you go into some sort of presentation mode.  See the minipres link for info and more examples.

Are either of these good enough?  plus, they should be documented in sphinx-lesson itself...

**Comment by robertodr** [comment]
Thanks for the suggestions! I didn't manage to install sphinx_minipres, but that's a problem on my end. `sphinx-book-theme` allows to collapse the side menu, but wreaks havoc with the directives of the lesson (everything is blue and all emojis are "info" emojis)

**Comment by rkdarst** [comment]
sphinx-minipres is a default dependency of sphinx-lesson, so I think
it should just work: https://enccs.github.io/intermediate-mpi/setup/?plain=1

**Comment by robertodr** [comment]
Indeed it does :sweat_smile:

**Comment by mabraham** [comment]
`?plain=1` looks very useful, thanks!
